channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake-minimal =9.6.2
  - jinja2
  - matplotlib
  - graphviz
  - pygments
  - pandas
  - pip:
    #  at the time of writing - 7. Feb 24 - pysam on bioconda will require
    #  a lower python version than snakemake, install pysam
    #  using pip
    - pysam
