#####################################
#
#       REFERENCE GENOME SETTINGS
#
#####################################
reference:
  # Specify the reference genome paths for each species
  # Corynebacterium_glutamicum_atcc_13032:                  ### The names follow the format of the SnpEff database
  #   name: "Corynebacterium_glutamicum_atcc_13032"
  #   path: "data/reference/Corynebacterium_glutamicum_atcc_13032/Corynebacterium_glutamicum_atcc_13032.fa"
  #   source: "GCF_000011325.1_ASM1132v1"
  species:
    name:
    path:
    source:

